os: linux
dist: focal

language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"

addons:
  apt:
    sources:
    - sourceline: 'deb http://ftp.indexdata.dk/ubuntu $TRAVIS_DIST main'
      key_url: http://ftp.indexdata.dk/debian/indexdata.asc
    packages:
    - yaz

before_install: yaz-marcdump -V

install: pip install -r requirements.txt -r requirements-dev.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pytest
