os: linux
dist: bionic

language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"

addons:
  apt:
    sources:
    - sourceline: 'deb http://ftp.indexdata.dk/ubuntu $TRAVIS_DIST main'
      key_url: http://ftp.indexdata.dk/debian/indexdata.asc
    packages:
    - yaz

before_install: yaz-marcdump -V

install: pip install -r requirements.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script: pytest
