name: test_python
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: pip install ruff
    - run: ruff --format=github .

  test_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]  # , macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run Python unit tests
        run: pytest
      - name: Mypy type checking
        run: mypy --ignore-missing-imports --install-types --non-interactive .
